force-app/main/default/objects/Study_Session__c/Study_Session__c.object-meta.xml
<CustomObject>
    <label>Study Session</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Study Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Session__c/fields/Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_Hours__c</fullName>
    <label>Duration(Hours)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_Session__c/fields/Study_Date__c.field-meta.xml
<CustomField>
    <fullName>Study_Date__c</fullName>
    <label>Study Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/StudySessionController.cls
public with sharing class StudySessionController {

    @AuraEnabled(cacheable=true)
    public static List<Study_Session__c> getStudySessions() {
        return [
            SELECT Id, Study_Date__c, Subject__c, Duration_Hours__c
            FROM Study_Session__c
            ORDER BY Study_Date__c DESC
        ];
    }
    @AuraEnabled
public static void createStudySession(Date studyDate, String subject, Decimal duration) {

    Study_Session__c session = new Study_Session__c(
        Study_Date__c = studyDate,
        Subject__c = subject,
        Duration_Hours__c = duration
    );

    insert session;
}
}